{"time":"2024-11-07T16:02:46.2867983+08:00","level":"INFO","msg":"using version","core version":"0.18.5"}
{"time":"2024-11-07T16:02:46.2867983+08:00","level":"INFO","msg":"created symlink","path":"D:\\Desktop\\hw4\\wandb\\run-20241107_160246-wt4plc48\\logs\\debug-core.log"}
{"time":"2024-11-07T16:02:46.5705181+08:00","level":"INFO","msg":"created new stream","id":"wt4plc48"}
{"time":"2024-11-07T16:02:46.5705181+08:00","level":"INFO","msg":"stream: started","id":"wt4plc48"}
{"time":"2024-11-07T16:02:46.5705181+08:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"wt4plc48"}}
{"time":"2024-11-07T16:02:46.5705181+08:00","level":"INFO","msg":"handler: started","stream_id":{"value":"wt4plc48"}}
{"time":"2024-11-07T16:02:46.5705181+08:00","level":"INFO","msg":"sender: started","stream_id":"wt4plc48"}
{"time":"2024-11-07T16:03:07.6287592+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:03:31.1058477+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:03:51.8348719+08:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2024-11-07T16:04:00.6988384+08:00","level":"INFO","msg":"stream: closing","id":"wt4plc48"}
{"time":"2024-11-07T16:04:00.6988384+08:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2024-11-07T16:04:00.6993745+08:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2024-11-07T16:04:11.2781224+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.82.21.23:52915->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:11.2781224+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.82.21.23:52915->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:11.2781224+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.82.21.23:52915->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:11.2781224+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.82.21.23:52915->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:20.9322459+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2679724483-zhejiang-university/Ultralytics/wt4plc48/file_stream\": read tcp 10.82.21.23:52984->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:34.3715266+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:34.3872918+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:34.4983075+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:34.5284536+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:44.043893+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2679724483-zhejiang-university/Ultralytics/wt4plc48/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:59.6472573+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:04:59.8055025+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:00.3550862+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:00.3550862+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:09.833683+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2679724483-zhejiang-university/Ultralytics/wt4plc48/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:29.9022512+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:30.3133896+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:30.3452319+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:31.2597137+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:05:39.8040148+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2679724483-zhejiang-university/Ultralytics/wt4plc48/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:06:07.5884914+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:06:09.6856582+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:06:10.0658574+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:06:11.0513278+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:06:18.5994069+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2679724483-zhejiang-university/Ultralytics/wt4plc48/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:07:13.8485648+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.82.21.23:53159->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:07:16.7905469+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2679724483-zhejiang-university/Ultralytics/wt4plc48/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:07:37.1534791+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:08:02.9935529+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:08:32.1141021+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:08:37.8240237+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/2679724483-zhejiang-university/Ultralytics/wt4plc48/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-07T16:09:10.0597619+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
